### ISSUE TITLE
Static array override in bit.c

### ISSUE THREAD

**Issue by Marmotte06** [abulmo/edax-reversi#22]
In the new bit.c (4.5.2), line 549, there is the following declaration:
static const char color[2] = ".X";

Which is wrong, since the ".X" string is 3 chars, not 2.

An easy fix is to declare:
static const char color[] = ".X";
and let the compiler figure the space needed.

**Comment by Marmotte06** [comment]
A similar problem appears in board.c; in the static declarations of the variables "color" and "piece"

**Comment by abulmo** [comment]
Sorry, the version 4.5.2 came from https://github.com/okuhara/edax-reversi-AVX. Edax 4.4 used:
const char *color = ".X";
and version 4.6 (in development) already uses:
const char color[] = ".X";
