### ISSUE TITLE
_InterlockedAdd64 intrinsic does not exist, neither in AMD64 intrinsics, nor in Visual Studio C++

### ISSUE THREAD

**Issue by Marmotte06** [abulmo/edax-reversi#23]
That code cannot compile in Visual Studio 2022, since the _InterlockedAdd64 intrinsic does not exist.

For the list of existing and valid intrinsics, see:
https://learn.microsoft.com/fr-fr/cpp/intrinsics/x64-amd64-intrinsics-list?view=msvc-170

And, anyway, the code is missing #include <intrin.h>
That was visibly never tested...

**Comment by abulmo** [comment]
_InterlockedAdd64 is an ARM instruction.
I do not see it in Edax code, so I do not understand your comments.

**Comment by Marmotte06** [comment]
It is used in util.h line 330:

#elif defined(USE_MSVC_X64)
	_InterlockedAdd64(value, i);
#else

**Comment by okuhara** [comment]
_InterlockedAdd64 is defined in <winnt.h>, which is included from <windows.h>
https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-_inlineinterlockedadd64
