### ISSUE TITLE
NWS_STABILITY_THRESHOLD not defined

### ISSUE THREAD

**Issue by Marmotte06** [abulmo/edax-reversi#24]
The NWS_STABILITY_THRESHOLD table is used in endgame.c, NWS_endgame routine, but isn't defined anywhere.

**Comment by okuhara** [comment]
This is my fault in the 4.5 mod.  I made the NWS_STABILITY_THRESHOLD public back in my repo as in the 4.4.
https://github.com/okuhara/edax-reversi-AVX/commit/b327e87a0ab3ff8b82a56b4ff59368ac4cafbb48
