### ISSUE TITLE
board_solve() not visible from endgame_sse.c

### ISSUE THREAD

**Issue by Marmotte06** [abulmo/edax-reversi#25]
The board_solve() routine is not visible from endgame_sse.c

But it is defined as static in endgame.c

The best solution is probably to define it as inline in a header, for instance board.h

**Comment by okuhara** [comment]
This also belongs to me.  That's why the endgame_sse.c is included in the middle of the endgame.c, but reading your comment, I removed the static in my repo.
https://github.com/okuhara/edax-reversi-AVX/commit/aa4b6a1394933b7e01bbf71648e08d1f8ad44b12
