### ISSUE TITLE
bit_count_32 useless and references __popcnt32 which doesn't exist for MSVC x64

### ISSUE THREAD

**Issue by Marmotte06** [abulmo/edax-reversi#26]
It seems that the bit_count_32 function defined in bit.c line 117 is no more use (EDAX 4.6 is full x64 now),
and, in addition, it references the __popcnt32 intrinsic which doesn't exist in MSVC x64, see:
https://learn.microsoft.com/en-us/cpp/intrinsics/popcnt16-popcnt-popcnt64?view=msvc-170

If really a 32 bit popcnt is needed for msvc, the right intrinsic seems to be __popcnt

**Comment by okuhara** [comment]
Unlike __builtin_popcountll/__builtin_popcount, __popcnt64/__popcnt is always compiled into hardware instruction, so it should be surrounded by conditional compilation.
