### ISSUE TITLE
Missing #include "board.h" in flip_avx_acepck.c

### ISSUE THREAD

**Issue by Marmotte06** [abulmo/edax-reversi#34]
This include is needed in order to have the "Board" type defined for the function board_flip()

**Comment by abulmo** [comment]
board.h is included in board.c before the inclusion of flip_avx_acepck.c, so there is no problem. The flip_*.c  & count_last_flip*.c should not be compiled separately (ie they should not be part of a project), they are included in board.c depending on the algorithm chosen (in settings.h).
