### ISSUE TITLE
__builtin_clzl is for unsigned long

### ISSUE THREAD

**Issue by okuhara** [abulmo/edax-reversi#43]
https://github.com/abulmo/edax-reversi/blob/8dbf3b6ca71c8ca7b461a9495daf2b7698142750/src/bit.c#L160
__builtin_clzll(b);
?

**Comment by okuhara** [comment]
It's OK if ABI is lp64, but safer to use the ll version.

**Comment by okuhara** [comment]
fixed in PR#43

**Comment by okuhara** [comment]
forgot fixing L354

**Comment by abulmo** [comment]
Right, windows uses LLP64  (well, windows compiler only), the rest of the world uses LP64 :-(
