### ISSUE TITLE
Edax will not completely solve 38 to 40 plys ahead

### ISSUE THREAD

**Issue by chunglimlee** [abulmo/edax-reversi#48]
Edax has a tendency to not 100% finish search ahead of certain plys.

For example, after 20 moves, search ply 40 will not even give you the option to actually solve it with indefinite time, but it just gives a 73% or something percentage (using "level 40" and hint "1"). It seems to have an auto cut off time to complete a search on its own.

**Comment by okuhara** [comment]
https://github.com/abulmo/edax-reversi/blob/de4b1e0ef5c2d7b5a9759a0aaace6b874eec266d/src/search.c#L309
To solve 40 empties, level should be set 46 or above.

**Comment by abulmo** [comment]
The level is not necessarily equal to a solving depth.  To solve exactly at any depth use level 60.
