### ISSUE TITLE
nboard pass not parsed

### ISSUE THREAD

**Issue by okuhara** [abulmo/edax-reversi#50]
I received an issue regarding nboard interface before:
https://github.com/okuhara/edax-reversi-AVX/issues/1
https://github.com/abulmo/edax-reversi/blob/de4b1e0ef5c2d7b5a9759a0aaace6b874eec266d/src/nboard.c#L142
My fix was:
```
			int lastmove = parse_ggf(&game, param);
			if (lastmove >= 0) {
				game_get_board(&game, 60, &play->initial_board);
				if (lastmove == PASS)
					board_pass(&play->initial_board);
```

**Comment by abulmo** [comment]
mine is :
 				i```
if (parse_ggf(&game, param, &pass) != param) {
		game_get_board(&game, 60, &play->initial_board);
		if (pass && board_is_pass(&play->initial_board)) board_pass(&play->initial_board);

```
It is more consistent with the way the other parse_ functions work.
