### ISSUE TITLE
4.6 solves ffo20-39 6 to 20% slower than 4.5 on Windows

### ISSUE THREAD

**Issue by okuhara** [abulmo/edax-reversi#51]
My test on linux in Mn/s (1 thread, ffo20-39):

| CPU | build | 4.6  |  4.5  | ratio |
| --- | --- | --- | --- | --- |
|  Haswell |  x86-64 | 29.17 | 32.46 | 0.899 |
|  Haswell |  x86-64-v2 (popcnt) | 30.57 | 33.04 | 0.925 |
|  Haswell |  x86-64-v3 (modern) | 35.97 | 37.40 | 0.961 |
| Ice Lake |  x86-64 | 30.88 | 32.74 | 0.943 |
| Ice Lake | x86-64-v3 (modern) | 38.63 | 38.65 | 0.999 |
| Ice Lake | x86-64-v4 (avx512) | 39.62 | 40.56 | 0.976 |
| Zen3 | x86-64 | 36.26 | 38.04 | 0.953 |
| Zen3 | x86-64-v3 (modern) | 44.38 | 46.21 | 0.960 |

On Windows (ratio is best/best):

| CPU | build | 4.6 (MSVC) | 4.6 (clang)  |  4.5 (MSVC) | 4.5 (clang)  | ratio |
| --- | --- | --- | --- | --- | --- | --- |
|  Haswell |  x86-64 | 31.75 | **31.88** | **40.28** | 39.62 | 0.791 |
|  Haswell |  x86-64-v2 (popcnt) | 34.02 | **34.71** | **41.25** | 38.97 | 0.841 |
|  Haswell |  x86-64-v3 (modern) | 36.14 | **39.30** | **46.39** | 45.17 | 0.847 |
| Ice Lake |  x86-64 | 22.23 | **26.93** | **32.62** | 31.22 | 0.826 |
| Ice Lake | x86-64-v3 (modern) | 29.02 | **33.54** | 35.25 | **35.83** | 0.936 |
| Ice Lake | x86-64-v4 (avx512) | 29.76 | **34.18** | **37.15** | 36.55 | 0.920 |
| Zen3 | x86-64 | **33.23** | 32.19 | 35.09 | **36.72** | 0.905 |
| Zen3 | x86-64-v3 (modern) | 35.39 | **39.95** | 42.52 | **43.51** | 0.918 |

While 4.6 was slower than 4.5 in all of my tests, speed degrade is much larger on Windows.
One advantage of x64 Windows ABI is non-volatile SSE registers, i.e. _m128i register variables.
I optimized for that in endgame_sse.c and endgame.c, those are dropped in 4.6.

**Comment by Marmotte06** [comment]
Mmmm, didn't you exchange the columns for 4.5 and 4.6 ? according to the tables above, it could seem that 4.6 is faster than 4.5.

On my side I didn't try 4.5, but I measure that 4.6 is 20% faster than 4.4 on Windows.
I was expecting more speedup. I suspect the C11 thread and synchronization mechanisms which are now used in 4.5 (4.4 was using the native Windows API), I am investigating this.

**Comment by okuhara** [comment]
Figures are in Mnode / sec, larger is better.
4.5 Windows modern build solves endgame 40% faster than 4.4, so your test is in accord with mine.
Here is the 4.5 binary: https://github.com/okuhara/edax-reversi-AVX/releases
My test is on single thread and thread performance is not evaluated.

**Comment by Marmotte06** [comment]
I use a modified version of the code with a Cython wrapper to make it a Python extension for my own purpose; hence I need to download your 4.5 code and customize it as I need. I'll do that in January.

**Comment by abulmo** [comment]
My results differs and the speed is close between the two versions for the problems in fforum-20-39 on a single thread :
4.5.3:
wEdax-x64.exe:        110168108 nodes in  0:02.219 (49647638 nodes/s).
wEdax-x64-modern.exe: 110222962 nodes in  0:01.860 (59259657 nodes/s).
wEdax-x86-sse.exe:    110168108 nodes in  0:03.110 (35423829 nodes/s).
wEdax-x86.exe:        110168108 nodes in  0:03.656 (30133509 nodes/s).
4.6:
wEdax-x86-64.exe:    111133009 nodes in  0:02.252 (cpu =  0:02.391) (49348583 nodes/s).
wEdax-x86-64-v2.exe: 111133009 nodes in  0:02.078 (cpu =  0:02.203) (53480755 nodes/s).
wEdax-x86-64-v3.exe: 111133009 nodes in  0:01.876 (cpu =  0:01.969) (59239344 nodes/s).

They were done on a single thread on a stock Ryzen 5600 cpu. The speeds are curiously much higher (> 30%) than in your examples. I used [clang]([https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.8) to compile them (the compilers from Microsoft are slower, but I only used the free versions, maybe the professional one are better). 

I will publish the final sources & executable tomorrow so you can test yourself.

What annoyed me in 4.5.3: the number of nodes is not the same across the versions so there is a bug somewhere. Many modifications were very complex without a measurable speed improvement, so I remove them or disable them (it is possible than on some cpu they are faster). Some algorithm are buggy. Some flip_ and count_last_flip_ are incompatible. The interface is not always the same.

**Comment by okuhara** [comment]
OK, I'll test your build later.  Regarding other points:

> The speeds are curiously much higher

My Zen3 test was on Azure D2asv5 instance, with 3.5GHz boost (compared to Ryzen 5600's 4.4GHz boost), and it could be lower when other users use the same CPU.

> the compilers from Microsoft are slower, but I only used the free versions

I also am using the Community edition (free for freeware development).  It uses same optimizer as a paid version.  If you didn't download recently, newer release may produce better code, just like clang.

> the number of nodes is not the same across the versions

The modern build and the avx512 build are built with LASTFLIP_HIGHCUT option enabled, which incleases node count slightly.  It's gain is not very big (see table in http://www.amy.hi-ho.ne.jp/okuhara/edaxopt.htm#lazycutoff ) and can be disabled on demand.

> Some algorithm are buggy

Please specify where is buggy.

**Comment by okuhara** [comment]
Here is a test result using your binary.
You're right, the 4.6 x86-64-v3 build runs almost equally fast as the 4.5.3 on AMD.
And as you expect, the 4.6 is sometimes slower than the 4.5.3 on Intel.

## x86-64-v3 (modern)

| CPU | 4.6 | 4.5.3 | ratio |
| --- | --- | --- | ---|
| Haswell (my local PC) | 46.46 | 48.33 | 0.961 |
| Saphire Lake (AWS c7i) | 42.81 | 47.62 | 0.899 |
| Ryzen 5600 (your PC) | 59.24 | 59.26 | 1.000 |
| Genoa (Azure D2alsv6) | 49.77 | 49.32 | 1.009 |

## x86-64 (x64)

| CPU | 4.6 | 4.5.3 | ratio |
| --- | --- | --- | ---|
| Haswell (my local PC) |  35.58 | 40.79 | 0.872 |
| Saphire Lake (AWS c7i) | 34.70 | 38.72 | 0.896 |
| Ryzen 5600 (your PC) | 49.35 | 49.65 | 0.994 |
| Genoa (Azure D2alsv6) | 35.55 | 35.98 | 0.988 |

**Comment by okuhara** [comment]
I cannot reproduce your executable with my clang 18; mine is 7 to 10% slower than yours.  This is the cause of the difference between my two tests.  Would you teach me your build process?
