### ISSUE TITLE
It seems Spurious Wakeups of threads are not handled

### ISSUE THREAD

**Issue by Marmotte06** [abulmo/edax-reversi#52]
Looking at ybwc.c and in particular at the two places where cnd_wait is used to wait on a condiftion, it seems Spurious Wakeups are not handled at all.

Spurious Wakeup of a thread is when the thread is activated without any real work to do. They don't happen on Linux Pthread, but THEY DO HAPPEN with Windows condition variables, either C11/17 or C++11/17/20:
https://en.cppreference.com/w/c/thread/cnd_wait
https://en.cppreference.com/w/cpp/thread/condition_variable

The correct way to deal with spurious wakeups is to have a Predicate that is tested in a loop around the wait()

Master thread:
there_is_work = true;
cnd_signal()

Slave thread:
while(true) {
   cnd_wait();
   if (there_is_work)
       do_work()
   }
   there_is_work = false;
}

nb. spurious wakeups happen because the Windows scheduler uses a hash table to find what thread(s) need to be activated when signalling/notifying a condition variable, hence when there are hash collisions wrong threads can be activated, and those threads must understand by themselves that they have is nothing to do and should wait again.

**Comment by abulmo** [comment]
the two cnd_wait are called to the  same scheme as above,  aren't they?

**Comment by Marmotte06** [comment]
The first cnd_wait, in node_wait_slaves(), is followed by the test
if (node->is_helping)
But, if node->is_helping is true when a spurious wakeup happens, there can be a problem.
I don't know the logic of your multi-threading, this is why I didn't change anything to the code.

The second cnd_wait is in task_loop(), and there are task->run tests around it.
But, as before, I do not know whether those tests are intended to handle spurious wakeups.
Only you know the logic of your multi-threading and can decide whether this is sufficient to avoid that a spurious wakeup results in a wrong call to task_search()

**Comment by abulmo** [comment]
I guess it's ok. if node->is_helping is true means the thread is doing nothing and is available to search something. 
In MS-Windows multithreading scaling looks ok to me. It is not perfect but is is a well known drawback of the YBWC algorithm.
