### ISSUE TITLE
Asking for help

### ISSUE THREAD

**Issue by sagesan** [abulmo/edax-reversi#8]
Hello,

I wanted to create a bot that would play against people over the internet, but ideally by feeding him the board state and getting the next move, so that many people can play at their own pace. And wrapping the communication over HTTP. I have done this for chess using Stockfish.

Is there any tutorial on how to work with the program, ideally with some examples? After downloading (the linux version), all I get is 'Illegal instruction' and the help is not exactly helpful.

How does the position notation work? How do I tell edax to tell me his next move? Can it also validate move from input?

Thank you for doing this project, it looks awesome!

**Comment by abulmo** [comment]
Edax does not support the uci protocol used by Stockfish, but it supports several protocols to communicate with a GUI:
- edax (its own protocol)
- nboard an Othello protocol designed by Chris Welty for its program Ntest and its GUI Nboard
- cassio an Othello protocol designed b Stephane Nicolet  http://cassio.free.fr/engine-protocol.htm
- gtp the go text protocol: http://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html
- xboard/winboard https://www.gnu.org/software/xboard/engine-intf.html
- ggs to comunicate directly with a generic game server (by Michael Buro & co).
Pick the one you prefer in the above list.
